package de.berlios.beanvalidator.validator;

import java.util.List;

/**
 * Core behaviors provided by all bean validators.
 * @author $Author$
 * @version $Revision$
 */
public interface Validator {
	/**
	 * Get list of errors generated by validation failures.
	 * @return List of validation errors
	 */
	public List<String> getErrors();

	/**
	 * Determine if bean is valid or not.
	 * @return Validation status (true = valid, false = invalid)
	 */
	public boolean isValid();

	/**
	 * Add property validation rule to Validator
	 * @param propertyName
	 * @param propertyRule
	 * @param isRequired
	 */
	public void addPropertyRule(String propertyName, String propertyRule, boolean isRequired);
}
